### ISSUE TITLE
older version works with trac trunk, newer one doesnt

### ISSUE THREAD

**Issue by fgnievinski** [trac-hacks/trac-mypage#1]
http://trac-hacks.org/browser/tracmypageplugin/0.11
https://github.com/mitar/trac-mypage

**Comment by mitar** [comment]
And what is the error? In what way it fails?

**Comment by mitar** [comment]
@rjollos, do you think we should move development here? I see you added some commits here: https://trac-hacks.org/log/tracmypageplugin

But I also fixed some issues in this repository.

**Comment by mitar** [comment]
Tested and it works for me.
